[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"
author = ["Marcus Sena <mens.eai20@uea.edu.br>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
